version: '3.7'

services:

  taxi-redis:
    container_name: taxi-redis
    image: redis:5.0.3-alpine

  taxi-server:
    build:
      context: ./server
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static
    command: daphne --bind 0.0.0.0 --port 8000 taxi.asgi:application
    container_name: taxi-server
    depends_on:
      - taxi-redis
    environment:
      - REDIS_URL=redis://taxi-redis:6379/0
    ports:
      - 8001:8000

  taxi-client:
    build:
      context: ./client
    command: ng serve --host 0.0.0.0
    container_name: taxi-client
    depends_on:
      - taxi-server
    environment:
      - CHROME_BIN=chromium-browser
    ports:
      - 4201:4200

  nginx:
    build:
      context: ./nginx
    container_name: taxi-nginx
    depends_on:
      - taxi-server
      - taxi-client
    ports:
      - 8080:80
    restart: always
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static

volumes:
  media:
  static: